# Generated by Django 4.1.4 on 2022-12-16 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('lat', models.CharField(blank=True, max_length=30, null=True)),
                ('long', models.CharField(blank=True, max_length=30, null=True)),
                ('street_address', models.TextField(max_length=300)),
                ('city', models.TextField(max_length=150)),
                ('state', models.TextField(max_length=150)),
                ('has_lng_lat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('lat', models.CharField(blank=True, max_length=30, null=True)),
                ('long', models.CharField(blank=True, max_length=30, null=True)),
                ('street_address', models.TextField(max_length=300)),
                ('city', models.TextField(max_length=150)),
                ('state', models.TextField(max_length=150)),
                ('has_lng_lat', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
