# Generated by Django 4.1.4 on 2022-12-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='street_address',
            field=models.TextField(max_length=150),
        ),
    ]
